"""Download a tiny Carto dark raster neighbourhood and pack it as MBTiles.

Honest limitation: Bangalore demo bbox only (~1 km), zooms 13-17 — NOT full India.
"""
from __future__ import annotations

import math
import sqlite3
import time
import urllib.request
from pathlib import Path

# Bangalore MG Road / Cubbon area — matches RelativeModeTest fixture (12.9716, 77.5946)
LAT_MIN, LAT_MAX = 12.9650, 12.9780
LON_MIN, LON_MAX = 77.5850, 77.6040
Z_MIN, Z_MAX = 13, 17
TILE_URL = "https://basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png"
UA = "SIH26168-IDR/1.0 (offline demo mbtiles build; contact: local-dev)"
OUT = Path("android/app/src/main/assets/maps/demo_neighbourhood.mbtiles")
README = Path("android/app/src/main/assets/maps/README.md")


def deg2num(lat_deg: float, lon_deg: float, zoom: int) -> tuple[int, int]:
    lat_rad = math.radians(lat_deg)
    n = 2.0**zoom
    xtile = int((lon_deg + 180.0) / 360.0 * n)
    ytile = int((1.0 - math.asinh(math.tan(lat_rad)) / math.pi) / 2.0 * n)
    return xtile, ytile


def tiles_for_bbox(z: int) -> list[tuple[int, int, int]]:
    x0, y1 = deg2num(LAT_MIN, LON_MIN, z)  # south-west → higher Y in XYZ
    x1, y0 = deg2num(LAT_MAX, LON_MAX, z)  # north-east → lower Y in XYZ
    xs = range(min(x0, x1), max(x0, x1) + 1)
    ys = range(min(y0, y1), max(y0, y1) + 1)
    return [(z, x, y) for x in xs for y in ys]


def xyz_to_tms_row(z: int, y: int) -> int:
    return (2**z) - 1 - y


def fetch(z: int, x: int, y: int) -> bytes:
    url = TILE_URL.format(z=z, x=x, y=y)
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def main() -> None:
    all_tiles: list[tuple[int, int, int]] = []
    for z in range(Z_MIN, Z_MAX + 1):
        ts = tiles_for_bbox(z)
        print(f"z{z}: {len(ts)} tiles")
        all_tiles.extend(ts)
    print(f"total tiles: {len(all_tiles)}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    if OUT.exists():
        OUT.unlink()

    con = sqlite3.connect(OUT)
    cur = con.cursor()
    cur.execute("CREATE TABLE metadata (name text, value text)")
    cur.execute(
        "CREATE TABLE tiles (zoom_level integer, tile_column integer, tile_row integer, tile_data blob)"
    )
    cur.execute(
        "CREATE UNIQUE INDEX tile_index ON tiles (zoom_level, tile_column, tile_row)"
    )
    meta = {
        "name": "IDR demo neighbourhood (Bangalore)",
        "format": "png",
        "type": "baselayer",
        "version": "1",
        "description": (
            "Small Carto dark_all raster pack for SIH tunnel demo. "
            "Bangalore bbox only -- not India-wide."
        ),
        "attribution": "(c) OpenStreetMap contributors (c) CARTO",
        "minzoom": str(Z_MIN),
        "maxzoom": str(Z_MAX),
        "bounds": f"{LON_MIN},{LAT_MIN},{LON_MAX},{LAT_MAX}",
        "center": f"{(LON_MIN + LON_MAX) / 2:.6f},{(LAT_MIN + LAT_MAX) / 2:.6f},16",
    }
    cur.executemany(
        "INSERT INTO metadata (name, value) VALUES (?, ?)", list(meta.items())
    )

    failed = 0
    for i, (z, x, y) in enumerate(all_tiles, 1):
        try:
            data = fetch(z, x, y)
            tms_y = xyz_to_tms_row(z, y)
            cur.execute(
                "INSERT INTO tiles (zoom_level, tile_column, tile_row, tile_data) VALUES (?,?,?,?)",
                (z, x, tms_y, data),
            )
        except Exception as e:
            failed += 1
            print(f"FAIL {z}/{x}/{y}: {e}")
        if i % 20 == 0:
            con.commit()
            print(f"  {i}/{len(all_tiles)}")
        time.sleep(0.05)  # be polite to Carto CDN

    con.commit()
    con.close()
    size_mb = OUT.stat().st_size / (1024 * 1024)
    print(f"wrote {OUT} ({size_mb:.2f} MiB), failed={failed}")

    README.write_text(
        f"""# Bundled offline basemap (P0-4)

`demo_neighbourhood.mbtiles` — small **raster** pack (Carto `dark_all` / OSM data)
for the Bangalore demo neighbourhood only.

| | |
|---|---|
| Bbox | ~{LAT_MIN}–{LAT_MAX} N, {LON_MIN}–{LON_MAX} E (MG Road / Cubbon area) |
| Zooms | {Z_MIN}–{Z_MAX} |
| NOT included | Full India, full city, vector tiles |

Generated by `tools/build_demo_mbtiles.py`. Re-run that script if you need a
different bbox. Airplane-mode demos outside this bbox will show empty tiles
(dark background) until live/cached tiles are available.
""",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
